# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Books

# Attribute name
nameFrom: title

# Model Class name
modelClass: Codalia\Bookend\Models\Ordering

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
